"""Bundled knowledge base of the top macOS / Linux / Windows commands.

howzo can only rank words that appear in indexed text. A tool whose man page
never uses the words users type is invisible: `cat`'s man page says
"concatenate files", so "content of the file" had no way to reach it. SEED
closes that gap with curated entries for the commands people reach for most,
merged into the inventory at scan time (see apply_seed).

Each entry is (name, platform, oneliner, when_to_use):
  name       the command as typed (Windows cmd / PowerShell names included)
  platform   "all" | "macos" | "linux" | "windows" — where the command is at
             home. Entries of every platform are indexed so a macOS user can
             still find `ipconfig`; foreign rows carry a ranking penalty
             (match.rank_rows) so the machine's own tools win.
  oneliner   one terse, factual, man-page-style sentence
  when_to_use 4-12 words of the phrasing users actually type. Intent-specific
             on purpose: stuffing generic words ("file", "text") into many
             entries creates ranking collisions.

Seed rows only fill gaps: a name that exists locally is never replaced, and a
row's own when_to_use/oneliner is only filled when it is empty — a value you
set yourself always wins.
"""
import sys

from . import config

ALL = "all"
MACOS = "macos"
LINUX = "linux"
WINDOWS = "windows"

SEED = [
    # ---- files and directories -------------------------------------------
    ("ls", ALL, "list directory contents",
     "list the files and folders in a directory"),
    ("cp", ALL, "copy files and directories",
     "copy a file or folder to another location"),
    ("mv", ALL, "move (rename) files",
     "rename or move a file or folder"),
    ("rm", ALL, "remove file system objects",
     "delete a file or folder, remove files and directories"),
    ("mkdir", ALL, "make directories",
     "create a new folder or directory"),
    ("rmdir", ALL, "remove empty directories",
     "delete an empty folder or directory"),
    ("ln", ALL, "make links between files",
     "create a symbolic link or shortcut"),
    ("touch", ALL, "change file access and modification times",
     "create an empty file, update a file timestamp"),
    ("cat", ALL, "concatenate files and print on the standard output",
     "show the contents of a file in full"),
    ("head", ALL, "display the first lines of a file",
     "show the first lines of a file, preview the beginning of a file"),
    ("tail", ALL, "display the last lines of a file",
     "show the last lines of a file, follow a log file as it grows"),
    ("wc", ALL, "print line, word, and byte counts",
     "count lines, words, and bytes in a file"),
    ("sort", ALL, "sort lines of text files",
     "sort the lines of a file or of command output"),
    ("uniq", ALL, "report or omit repeated lines",
     "remove duplicate lines from sorted text"),
    ("cut", ALL, "cut out selected portions of each line",
     "extract a column or field from text"),
    ("paste", ALL, "merge lines of files",
     "join lines from two text streams side by side"),
    ("tr", ALL, "translate or delete characters",
     "replace or remove characters in a stream of text"),
    ("sed", ALL, "stream editor",
     "find and replace text, edit a stream line by line"),
    ("awk", ALL, "pattern-directed scanning and processing language",
     "filter and transform columns of text"),
    ("grep", ALL, "print lines that match a pattern",
     "search for lines that match a pattern in file contents, command output, or log files"),
    ("find", ALL, "walk a file hierarchy",
     "search the file system for files by name, size, or age and act on them"),
    ("xargs", ALL, "construct argument lists and execute a utility",
     "run a command on every result of a search"),
    ("file", ALL, "determine the type of a path or stream",
     "identify what kind of data a path holds (magic bytes)"),
    ("stat", ALL, "display file status",
     "show the size and timestamps of a file"),
    ("du", ALL, "display disk usage statistics",
     "how much space a directory or file takes, disk usage of a folder"),
    ("df", ALL, "display free disk space",
     "check disk space, free space on a volume, how full the disk is"),
    ("chmod", ALL, "change file modes",
     "make a script executable, change file permissions"),
    ("chown", ALL, "change file owner and group",
     "change who owns a file or folder"),
    ("tee", ALL, "read standard input and write to standard output and files",
     "write command output to a file and the screen"),
    ("seq", ALL, "print sequences of numbers",
     "print a range of numbers"),
    ("expr", ALL, "evaluate expressions",
     "do arithmetic in the shell"),
    ("sleep", ALL, "suspend execution for an interval",
     "pause a script or command for a while"),
    ("date", ALL, "display or set the date and time",
     "print the current date and time"),
    ("cal", ALL, "display a calendar",
     "print a calendar for a month or year"),
    ("clear", ALL, "clear the terminal screen",
     "clear the terminal screen"),
    ("history", ALL, "display the command history list",
     "see the commands you ran before"),
    ("less", ALL, "view text one screen at a time",
     "scroll through a long log or output page by page"),
    ("more", ALL, "page through text one screen at a time",
     "page through long output with the older pager"),
    ("open", MACOS, "open files and directories in their default application",
     "open a document, folder, or url in its app (macOS)"),
    ("echo", ALL, "write arguments to the standard output",
     "print text or the value of a variable"),
    ("env", ALL, "set the environment for a command, or print it",
     "show or set environment variables for a command"),
    ("printenv", ALL, "print out the environment",
     "print the value of an environment variable"),
    ("export", ALL, "set an environment variable in the shell",
     "set an environment variable for this shell"),
    ("pwd", ALL, "print working directory name",
     "print the path of the current folder"),
    ("cd", ALL, "change the working directory",
     "change to another directory, go to a folder"),
    ("basename", ALL, "return the filename portion of a pathname",
     "strip the directories from a path"),
    ("dirname", ALL, "return the directory portion of a pathname",
     "strip the filename from a path"),
    ("split", ALL, "split a file into pieces",
     "split a large file into smaller parts"),
    ("diff", ALL, "compare files line by line",
     "compare two files and show the differences"),
    ("cmp", ALL, "compare two files byte by byte",
     "check whether two files are identical"),
    ("md5sum", LINUX, "compute and check MD5 message digests",
     "get the checksum or hash of a file (Linux)"),
    ("md5", MACOS, "compute the MD5 checksum of a file",
     "get the md5 checksum or hash of a file (macOS)"),
    ("shasum", ALL, "print or check SHA checksums",
     "get the sha256 hash of a file, verify an integrity checksum"),
    ("base64", ALL, "base64 encode or decode data",
     "encode or decode base64 data"),
    ("strings", ALL, "find printable strings in a file",
     "extract readable text from a binary file"),
    ("which", ALL, "locate a command in the PATH",
     "find where a command is installed"),
    ("whereis", ALL, "locate the binary, source, and manual page for a command",
     "find where a program and its manual are installed"),
    ("man", ALL, "display the on-line manual pages",
     "read the manual or documentation for a command"),
    ("help", ALL, "display help for shell built-ins and commands",
     "get help on a shell built-in"),
    ("watch", LINUX, "execute a program periodically, showing output fullscreen",
     "run a command repeatedly and watch its output"),
    ("timeout", LINUX, "run a command with a time limit",
     "stop a command automatically after a given time"),
    # ---- processes --------------------------------------------------------
    ("ps", ALL, "process status",
     "list running processes, what is running, cpu and memory usage of a process"),
    ("top", ALL, "display and update sorted information about processes",
     "watch running processes live, cpu and memory usage, find a runaway process"),
    ("kill", ALL, "terminate or signal a process",
     "stop or terminate a process, send a signal to a process"),
    ("killall", ALL, "kill processes by name",
     "stop every running program whose name matches"),
    ("pgrep", ALL, "find or signal processes by name",
     "look up the process id of a running program"),
    ("pkill", ALL, "kill processes by name and pattern",
     "kill every running program matching a pattern"),
    ("htop", ALL, "interactive process viewer",
     "watch memory and cpu interactively"),
    ("nohup", ALL, "invoke a command immune to hangups",
     "keep a command running after you log out"),
    ("time", ALL, "time a command's execution",
     "measure how long a command takes"),
    ("uptime", ALL, "show how long the system has been running",
     "check system load and how long it has been up"),
    # ---- users, host, system ---------------------------------------------
    ("whoami", ALL, "print the effective user name",
     "print the current user name"),
    ("id", ALL, "print real and effective user and group identities",
     "show your user id and group memberships"),
    ("groups", ALL, "show group memberships",
     "list the groups your user belongs to"),
    ("hostname", ALL, "set or print the name of the current host",
     "show or set the machine name"),
    ("uname", ALL, "print operating system name and version",
     "show the os name, version, and machine architecture"),
    ("w", ALL, "show who is logged on and what they are doing",
     "see who is logged in and what they are running"),
    ("who", ALL, "display who is logged on",
     "see who is logged in"),
    ("sudo", ALL, "execute a command as another user",
     "run a command as root or another user"),
    ("su", ALL, "substitute user identity",
     "switch to another user account"),
    ("mount", ALL, "mount file systems",
     "attach a disk or filesystem"),
    ("umount", ALL, "unmount file systems",
     "detach a mounted disk or filesystem"),
    ("crontab", ALL, "maintain crontab files",
     "schedule a command to run on a timer"),
    ("sysctl", ALL, "get or set kernel state",
     "read kernel tunables, change system parameters"),
    ("screen", ALL, "screen manager with terminal emulation",
     "keep a session running after disconnecting"),
    ("tmux", ALL, "terminal multiplexer",
     "split the terminal into panes, keep sessions alive"),
    ("sqlite3", ALL, "command-line interface to SQLite databases",
     "query a sqlite database file"),
    ("openssl", ALL, "cryptography and SSL/TLS toolkit",
     "inspect a certificate, generate keys, encrypt data"),
    ("gpg", ALL, "GNU privacy guard",
     "encrypt or sign a message, manage pgp keys"),
    ("ssh-keygen", ALL, "authentication key generation and management",
     "create an ssh key pair for logins"),
    # ---- networking -------------------------------------------------------
    ("curl", ALL, "transfer a URL",
     "download files from the web, make http requests, transfer a url"),
    ("wget", ALL, "non-interactive network downloader",
     "download a url over http or ftp"),
    ("ssh", ALL, "OpenSSH remote login client",
     "connect to a remote server, run commands over ssh, secure copy with scp"),
    ("scp", ALL, "secure copy (remote file copy program)",
     "copy files to or from a remote server"),
    ("sftp", ALL, "secure file transfer program",
     "transfer files to a remote server interactively"),
    ("rsync", ALL, "remote file-copy and synchronization tool",
     "sync or mirror folders, copy changes over ssh"),
    ("ping", ALL, "send ICMP echo requests to network hosts",
     "check whether a host is reachable, test network latency"),
    ("dig", ALL, "DNS lookup utility",
     "look up dns records for a domain"),
    ("nslookup", ALL, "query internet name servers interactively",
     "look up a domain name or ip address at a dns server"),
    ("traceroute", ALL, "print the route packets take to a network host",
     "trace the network path to a host"),
    ("mtr", ALL, "combine ping and traceroute in one diagnostic tool",
     "watch the network path and packet loss to a host"),
    ("ifconfig", ALL, "configure network interface parameters",
     "find or change your ip address, network interface (en0/wlan0 on macOS), mac address, dhcp"),
    ("ip", LINUX, "show and manipulate routing, network devices, interfaces",
     "show ip addresses and interfaces (Linux: ip addr)"),
    ("netstat", ALL, "show network connections and routing tables",
     "open ports, listening sockets, network connections"),
    ("route", ALL, "manipulate the network routing tables",
     "default gateway, routing table"),
    ("arp", ALL, "display and modify the ARP table",
     "mac address behind an ip, arp table"),
    ("lsof", ALL, "list open files",
     "find which process is using a file or a port"),
    ("iftop", ALL, "display bandwidth usage on an interface",
     "watch bandwidth usage per connection on an interface"),
    ("nc", ALL, "arbitrary TCP and UDP connections and listens (netcat)",
     "open a raw tcp connection, test whether a port is open"),
    ("ss", ALL, "investigate sockets",
     "show socket statistics and listening ports"),
    ("tcpdump", ALL, "dump traffic on a network",
     "capture and inspect network packets"),
    # ---- packages and containers -----------------------------------------
    ("brew", MACOS, "the missing package manager for macOS (Homebrew)",
     "install a package or command-line tool on macOS"),
    ("apt", LINUX, "APT package handling utility",
     "install or update packages on debian and ubuntu"),
    ("dpkg", LINUX, "Debian package manager",
     "inspect or install a .deb package file"),
    ("pip", ALL, "install and manage Python packages",
     "install a python library or package"),
    ("pipx", ALL, "install and run Python applications in isolated environments",
     "install a python command-line tool globally"),
    ("npm", ALL, "the node package manager",
     "install a node package or javascript dependency"),
    ("yarn", ALL, "package manager for JavaScript",
     "install javascript dependencies with yarn"),
    ("pnpm", ALL, "fast, disk space efficient package manager",
     "install node dependencies with pnpm"),
    ("npx", ALL, "execute a package binary from npm",
     "run a node package without installing it"),
    ("docker", ALL, "manage containers and images",
     "run or manage a container"),
    ("podman", ALL, "manage pods, containers and images",
     "run containers without a daemon"),
    ("uv", ALL, "an extremely fast Python package and project manager",
     "create a python project, install python dependencies fast"),
    ("cargo", ALL, "the Rust package manager",
     "build or install a rust crate"),
    # ---- languages and build ---------------------------------------------
    ("python", ALL, "an interpreted, interactive, object-oriented language",
     "run a python script or start a python repl"),
    ("python3", ALL, "the Python 3 interpreter",
     "run a python script with the python 3 interpreter"),
    ("node", ALL, "server-side JavaScript runtime",
     "run a javascript file or start a node repl"),
    ("ruby", ALL, "object-oriented scripting language",
     "run a ruby script or start a repl"),
    ("perl", ALL, "practical extraction and report language",
     "run a perl script or one-liner"),
    ("php", ALL, "the PHP command line interface",
     "run a php script from the command line"),
    ("java", ALL, "launch a Java application",
     "run a java program or a jar file"),
    ("go", ALL, "manage Go source code and build programs",
     "build or run a go program, manage go modules"),
    ("rustc", ALL, "the Rust compiler",
     "compile a rust source file"),
    ("gcc", ALL, "GNU project C and C++ compiler",
     "compile a C or C++ program"),
    ("clang", ALL, "C, C++ and Objective-C compiler",
     "compile a C or Objective-C program"),
    ("make", ALL, "maintain groups of programs",
     "build a project from a Makefile"),
    ("cmake", ALL, "cross-platform build system generator",
     "configure and generate a build system"),
    # ---- text, data, editors, vcs ----------------------------------------
    ("jq", ALL, "command-line JSON processor",
     "query, filter, and transform json documents; parse api responses"),
    ("yq", ALL, "a portable command-line YAML processor",
     "edit or query a yaml file from the command line"),
    ("tree", ALL, "list contents of directories in a tree-like format",
     "show the folder structure as a tree"),
    ("bat", ALL, "a cat clone with syntax highlighting and Git integration",
     "preview a source file with syntax highlighting and line numbers"),
    ("fd", ALL, "a simple, fast and user-friendly alternative to find",
     "search a directory tree quickly for names matching a pattern"),
    ("rg", ALL, "recursively search the current directory for a regex pattern",
     "search text in a directory quickly (ripgrep)"),
    ("fzf", ALL, "a command-line fuzzy finder",
     "fuzzy search through a list interactively"),
    ("zsh", ALL, "the Z shell",
     "switch to or configure the zsh shell"),
    ("bash", ALL, "GNU Bourne-Again SHell",
     "run a shell script or start a bash prompt"),
    ("fish", ALL, "the friendly interactive shell",
     "run the fish shell with autosuggestions"),
    ("vim", ALL, "vi improved, a programmers text editor",
     "edit text in the terminal"),
    ("nano", ALL, "nano's ANOther text editor, inspired by Pico",
     "edit text with a simple terminal editor"),
    ("emacs", ALL, "the extensible, customizable display editor",
     "edit text in emacs"),
    ("code", ALL, "Visual Studio Code",
     "open a project in VS Code"),
    ("git", ALL, "the stupid content tracker (version control)",
     "undo a commit, manage branches, version control history"),
    ("gitk", ALL, "the git repository browser",
     "browse the history of a git repository"),
    # ---- archives and media ----------------------------------------------
    ("tar", ALL, "manipulate tape archives",
     "create or extract an archive of files and folders (tar)"),
    ("zip", ALL, "package and compress (archive) files",
     "compress files and folders into a zip archive"),
    ("unzip", ALL, "list, test and extract compressed files in a ZIP archive",
     "extract the contents of a zip file"),
    ("gzip", ALL, "compression/decompression tool using Lempel-Ziv coding",
     "compress a single file down to a .gz"),
    ("bzip2", ALL, "block-sorting file compressor",
     "compress a file with bzip2"),
    ("xz", ALL, "compress or decompress .xz files",
     "compress a file with xz"),
    ("7z", ALL, "7-Zip file archiver",
     "create or extract a 7z archive"),
    ("sips", MACOS, "scriptable image processing system",
     "convert, resize, rotate, or crop an image file; export an image to pdf (macOS)"),
    ("convert", LINUX, "convert between image formats (ImageMagick)",
     "convert or resize an image file on the command line"),
    ("ffmpeg", ALL, "video and audio converter",
     "convert or trim a video or audio file"),
    ("pdftotext", ALL, "convert PDF files to plain text",
     "extract the text out of a pdf file"),
    # ---- macOS specifics ---------------------------------------------------
    ("pbcopy", MACOS, "copy standard input to the macOS clipboard",
     "copy command output to the clipboard (macOS)"),
    ("pbpaste", MACOS, "paste the macOS clipboard to standard output",
     "paste the clipboard into a command (macOS)"),
    ("launchctl", MACOS, "control macOS launchd services and jobs",
     "start, stop, or list background services on macOS"),
    ("diskutil", MACOS, "disk and volume management utility",
     "erase or repair a disk, list volumes on macOS"),
    ("hdiutil", MACOS, "manipulate disk images",
     "mount or create a dmg image (macOS)"),
    ("sw_vers", MACOS, "print macOS version information",
     "show which version of macOS is installed"),
    ("system_profiler", MACOS, "report system hardware and software configuration",
     "check hardware specs and installed software on macOS"),
    ("mdfind", MACOS, "find files matching a given query (Spotlight)",
     "search the whole machine with spotlight"),
    ("caffeinate", MACOS, "prevent the system from sleeping",
     "stop the mac from sleeping during a long job"),
    ("networksetup", MACOS, "configuration tool for network settings",
     "change wifi or dns settings on macOS"),
    ("pmset", MACOS, "manipulate power management settings",
     "check or change sleep and battery settings on macOS"),
    ("softwareupdate", MACOS, "system software update tool",
     "install macOS system updates from the command line"),
    # ---- Linux specifics ---------------------------------------------------
    ("systemctl", LINUX, "control the systemd system and service manager",
     "start, stop, or enable a service on linux"),
    ("journalctl", LINUX, "query the systemd journal",
     "read system logs on linux"),
    ("service", LINUX, "run a System V init script",
     "restart a service on linux"),
    ("lsblk", LINUX, "list block devices",
     "list disks and partitions on linux"),
    ("free", LINUX, "display memory usage",
     "check free and used memory"),
    ("users", ALL, "list the users logged in right now",
     "see which users are logged in, who is on the machine"),
    # memory, macos-flavoured - these had no curated intent at all, so the
    # matcher was reaching them only through their *names* ("memory" matched
    # memory_pressure by prefix). With names claimed exactly, the intent has to
    # be written down: see docs/design/matching-rebuild.md.
    ("memory_pressure", MACOS, "report and simulate macOS memory pressure",
     "watch memory usage, check how much memory is free, see memory pressure (macOS)"),
    ("vm_stat", MACOS, "show Mach virtual memory statistics",
     "see free memory, pages and paging activity on macOS"),
    ("leaks", MACOS, "search a process's memory for unreleased allocations",
     "find memory leaks in a running program (macOS)"),
    ("networkQuality", MACOS, "measure network download and upload speed",
     "test internet speed from the terminal on macOS"),
    # ---- Windows: cmd.exe --------------------------------------------------
    ("dir", WINDOWS, "list directory contents (cmd.exe)",
     "list the files and folders in a directory (cmd)"),
    ("cls", WINDOWS, "clear the screen (cmd.exe)",
     "clear the terminal screen on Windows"),
    ("type", WINDOWS, "display the contents of a text file (cmd.exe)",
     "display the contents of a text file (cmd)"),
    ("findstr", WINDOWS, "search for strings in files (cmd.exe)",
     "search for text inside files on Windows"),
    ("del", WINDOWS, "delete one or more files (cmd.exe)",
     "erase one or more files in cmd (Windows)"),
    ("erase", WINDOWS, "delete one or more files (cmd.exe)",
     "erase one or more files in cmd (Windows)"),
    ("rd", WINDOWS, "remove a directory (cmd.exe)",
     "remove an empty folder in cmd"),
    ("md", WINDOWS, "create a directory (cmd.exe)",
     "create a new folder in cmd"),
    ("copy", WINDOWS, "copy one or more files (cmd.exe)",
     "copy files with the cmd shell"),
    ("move", WINDOWS, "move files and rename directories (cmd.exe)",
     "move files with the cmd shell"),
    ("rename", WINDOWS, "rename a file or directory (cmd.exe)",
     "rename a file or folder (cmd)"),
    ("mklink", WINDOWS, "create a symbolic link (cmd.exe)",
     "create a symbolic link on Windows"),
    ("notepad", WINDOWS, "edit text files with Notepad",
     "edit a text file with notepad"),
    ("ipconfig", WINDOWS, "view and control IP configuration state",
     "show your ip address (Windows: ipconfig /all)"),
    ("tracert", WINDOWS, "trace the route to a host (Windows)",
     "trace the network path to a host on Windows"),
    ("tasklist", WINDOWS, "list running processes (Windows)",
     "list running processes on Windows"),
    ("taskkill", WINDOWS, "kill a process by name or pid (Windows)",
     "kill a process on Windows"),
    ("where", WINDOWS, "locate a command in the PATH (Windows)",
     "find the path of a command on Windows"),
    ("set", WINDOWS, "set or display environment variables (cmd.exe)",
     "show or set environment variables in cmd"),
    ("setx", WINDOWS, "set environment variables permanently (Windows)",
     "set a persistent environment variable on Windows"),
    ("compact", WINDOWS, "compress NTFS files and directories (Windows)",
     "compress files on an ntfs volume"),
    ("cipher", WINDOWS, "encrypt or decrypt NTFS files (Windows)",
     "encrypt a folder on Windows"),
    ("winget", WINDOWS, "the Windows Package Manager",
     "install a package with winget"),
    ("choco", WINDOWS, "the Chocolatey package manager",
     "install a package with chocolatey"),
    ("wsl", WINDOWS, "run Linux inside Windows (Windows Subsystem for Linux)",
     "run linux commands inside Windows"),
    ("powershell", WINDOWS, "PowerShell command-line shell",
     "run a powershell script or command"),
    ("cmd", WINDOWS, "the Windows command prompt",
     "open the command prompt on Windows"),
    # ---- Windows: PowerShell cmdlets --------------------------------------
    ("Get-ChildItem", WINDOWS, "list the items in a location (PowerShell)",
     "list files and folders in a directory (PowerShell)"),
    ("Get-Process", WINDOWS, "get the processes running on the machine",
     "list running processes on Windows"),
    ("Stop-Process", WINDOWS, "stop one or more running processes",
     "kill a process by name or id on Windows"),
    ("Get-Service", WINDOWS, "get the services on the machine",
     "check whether a service is running on Windows"),
    ("Start-Service", WINDOWS, "start a stopped service",
     "start a windows service"),
    ("Copy-Item", WINDOWS, "copy an item to a new location",
     "copy a file or folder in PowerShell"),
    ("Move-Item", WINDOWS, "move an item to a new location",
     "move or rename a file in PowerShell"),
    ("Remove-Item", WINDOWS, "delete an item",
     "delete a file or folder in PowerShell"),
    ("New-Item", WINDOWS, "create a new item",
     "create a file or folder in PowerShell"),
    ("Select-String", WINDOWS, "find text and patterns in strings and files",
     "search inside files with a pattern in PowerShell"),
    ("Format-Table", WINDOWS, "format output as a table",
     "print command output as a table"),
    ("Format-List", WINDOWS, "format output as a list of properties",
     "print every property of an object as a list"),
    ("Import-Csv", WINDOWS, "read a csv file into objects",
     "read a csv file as a table in PowerShell"),
    ("Export-Csv", WINDOWS, "write objects to a csv file",
     "write command output to a csv file"),
    ("ConvertTo-Json", WINDOWS, "convert an object to a json string",
     "turn an object into json in PowerShell"),
    ("Get-Content", WINDOWS, "read the contents of a file",
     "show the contents of a text file in PowerShell"),
    ("Set-Content", WINDOWS, "write content to a file",
     "write text to a file in PowerShell"),
    ("Out-File", WINDOWS, "send output to a file",
     "save command output to a file in PowerShell"),
    ("Measure-Object", WINDOWS, "count and measure object properties",
     "count lines, words, and characters of input"),
    ("Get-Command", WINDOWS, "get the commands available on the system",
     "check whether a command exists on Windows"),
]


def current_platform():
    """The platform howzo is running on: 'macos', 'linux', or 'windows'."""
    return config.platform_name()


_BY_NAME = {e[0]: e for e in SEED}


def entry(name):
    """The SEED tuple (name, platform, oneliner, when_to_use) for name."""
    return _BY_NAME.get(name)


def apply_seed(c, platform=None):
    """Merge SEED into the inventory; never clobber a local row's own text.

    A name that exists locally (source != 'seed') is left alone: the seed
    only fills an empty when_to_use / empty oneliner, and only when the entry
    is native to the running platform or marked 'all'. A local row that still
    carries a platform tag (it was seeded before the tool got installed) is
    cleared — a scanned row is native. Missing names are inserted as
    source='seed' with their platform recorded; their text is curated, so
    rescan re-syncs it from the bundled data (there is no user-facing editor
    for seed rows). Local rows' own text is never touched.

    Returns the number of rows written (inserted + filled).
    """
    plat = platform or current_platform()
    written = 0
    for name, entry_platform, oneliner, when_to_use in SEED:
        row = c.execute("SELECT source, oneliner, when_to_use, platform FROM tools WHERE name=?",
                        (name,)).fetchone()
        if row is not None and row["source"] != "seed":
            # a local row must never carry a seed's foreign tag, even if it
            # became installed after an earlier scan seeded it (self-heal)
            if row["platform"]:
                written += c.execute("UPDATE tools SET platform=NULL WHERE name=?",
                                     (name,)).rowcount
            if entry_platform in (ALL, plat):
                if not (row["when_to_use"] or ""):
                    written += c.execute(
                        "UPDATE tools SET when_to_use=? WHERE name=? AND when_to_use=''",
                        (when_to_use, name)).rowcount
                if not (row["oneliner"] or ""):
                    written += c.execute(
                        "UPDATE tools SET oneliner=? WHERE name=? AND oneliner=''",
                        (oneliner, name)).rowcount
            continue
        if row is None:
            c.execute("INSERT INTO tools(name, source, version, path, oneliner, when_to_use, platform) "
                      "VALUES(?,?,?,?,?,?,?)",
                      (name, "seed", "", "", oneliner, when_to_use, entry_platform))
            written += 1
        elif (row["oneliner"], row["when_to_use"], row["platform"]) != \
                (oneliner, when_to_use, entry_platform):
            # re-sync curated text on version bumps; skip no-ops so the
            # return value counts real writes
            c.execute("UPDATE tools SET oneliner=?, when_to_use=?, platform=? WHERE name=?",
                      (oneliner, when_to_use, entry_platform, name))
            written += 1
    return written
